# Generated by Django 3.2.22 on 2023-11-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20231105_1334'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cometary',
            new_name='Comentary',
        ),
    ]
